soccer/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('soccerApp.urls')),
    url(r'^admin/', admin.site.urls),
]

soccerApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'soccerApp'

urlpatterns = [
    
    # index 
    url(r'^$',views.IndexView.as_view(),name='index'),
    
    #/statics
    url(r'^statics$',views.StaticsView.as_view(),name='statics'),


    #/team/12
    url(r'^team/(?P<pk>[0-9]+)/$',views.DetailsView.as_view(),name='details'),


]

soccerApp/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse



class Team(models.Model):
	"""docstring for Team"""
	nameTeam = models.CharField(max_length=200)
	summary = models.CharField(max_length=400)
	playedGames = models.IntegerField(default=0)
	totalPoint = models.IntegerField(default=0)
	totalVictories = models.IntegerField(default=0)


	def __str__(self):
		return self.nameTeam

	def setTotalPoint(self,name, val):
		team=Team.objects.get(nameTeam = name)
		team.totalPoint +=val
		if(val!=1):
			team.totalVictories +=1
		team.save()

	def setPlayedGames(self,name):
		team=Team.objects.get(nameTeam = name)
		team.playedGames +=1
		team.save()

	def pair(x):
		return not bool(x % 2)

	def save(self, *args, **kwargs):
		ch=""

		myList=Team.objects.order_by('-totalPoint')
		for i,elt in enumerate(myList) :
			print (str(i)+""+elt.nameTeam)
			if not bool(i % 2):
				ch += " | "+elt.nameTeam
			else:
				ch += " VS "+elt.nameTeam

		print (ch)
		listOfMatch = Match.objects.all()
		for match in listOfMatch:
			match.setList(ch)

		super(Team, self).save(*args, **kwargs)



		

class Player(models.Model):
	"""docstring for Player"""
	namePlayer = models.CharField(max_length=200)
	nbGoal = models.IntegerField()
	team = models.ForeignKey(Team, on_delete=models.CASCADE)	
	def __str__(self):
		return self.namePlayer
		

class Match(models.Model):
	"""docstring for Match"""
	
	team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team1')
	team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team2')
	date = models.DateTimeField()
	nbGoals1 = models.IntegerField()
	nbGoals2 = models.IntegerField()
	list1 = models.CharField(max_length=200,default="ho")
	list2 = models.CharField(max_length=200,default="ho")

	def save(self, *args, **kwargs):
		if (self.nbGoals1 > self.nbGoals2):
			self.team1.setTotalPoint(self.team1.nameTeam,2)
		if (self.nbGoals1 < self.nbGoals2):
			self.team2.setTotalPoint(self.team2.nameTeam,2)
		if (self.nbGoals1 == self.nbGoals2):
			self.team1.setTotalPoint(self.team1.nameTeam,1)
			self.team2.setTotalPoint(self.team2.nameTeam,1)
		self.team1.setPlayedGames(self.team1.nameTeam)
		self.team2.setPlayedGames(self.team2.nameTeam)
		super(Match, self).save(*args, **kwargs)

	def setList(self,listp, *args, **kwargs):
		self.list1=listp
		super(Match, self).save(*args, **kwargs)



	def clean(self):
		if self.team1 == self.team2:
			raise ValidationError('the two teams cannot be the same')


	def __str__(self):
		return self.team1.nameTeam+" VS "+self.team2.nameTeam
		

soccerApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Team, Player, Match
from datetime import timedelta
from django.utils import timezone
from django.db.models import Max, Min, Sum

from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class IndexView(generic.ListView):
    """docstring for IndexView"""

    template_name = None
    context_object_name = None
    maxPoints = None

    def process(self):
        self.template_name = 'soccerApp/index.html'
        self.context_object_name = "all_teams"
        self.maxPoints = Team.objects.order_by('-totalPoint')[0].totalPoint

    def get_context_data(self, **kwargs):
        self.process()
        context = super(IndexView, self).get_context_data(**kwargs)
        context['maxPoints'] = self.maxPoints
        return context

    def get_queryset(self):
        return Team.objects.order_by('-totalPoint', 'playedGames')


class DetailsView(generic.DetailView):
    """docstring for DetailsView"""
    model = Team
    template_name = 'soccerApp/details.html'


class StaticsView(generic.ListView):
    """docstring for IndexView"""
    template_name = 'soccerApp/statics.html'
    context_object_name = "all_matchs"
    some_day_last_week = None
    monday_of_last_week = None
    monday_of_this_week = None
    # if (Match.objects.filter(date__gte=monday_of_last_week, date__lt=monday_of_this_week)):
    minGoal1 = None
    minGoal2 = None
    maxGoal1 = None
    maxGoal2 = None
    nbrMatch = None
    sumGoal = None
    bestTeam = None
    badTeam = None
    maxPoints = None
    minPoints = None

    def process(self):
        self.template_name = 'soccerApp/statics.html'
        self.context_object_name = "all_matchs"
        self.some_day_last_week = timezone.now().date() - timedelta(days=7)
        self.monday_of_last_week = self.some_day_last_week - timedelta(days=(self.some_day_last_week.isocalendar()[2] - 1))
        self.monday_of_this_week = self.monday_of_last_week + timedelta(days=7)
        # if (Match.objects.filter(date__gte=monday_of_last_week, date__lt=monday_of_this_week)):
        self.minGoal1 = \
        Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).order_by('nbGoals1')[
            0].nbGoals1
        self.minGoal2 = \
        Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).order_by('nbGoals2')[
            0].nbGoals2
        self.maxGoal1 = \
        Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).order_by('-nbGoals1')[
            0].nbGoals1
        self.maxGoal2 = \
        Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).order_by('-nbGoals2')[
            0].nbGoals2
        self.nbrMatch = Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).count()
        self.sumGoal = Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week).aggregate(
            Sum('nbGoals1'))
        self.bestTeam = Team.objects.order_by('-totalPoint', 'playedGames')[0].nameTeam
        self.badTeam = Team.objects.order_by('totalPoint')[0].nameTeam
        self.maxPoints = Team.objects.order_by('-totalPoint')[0].totalPoint
        self.minPoints = Team.objects.order_by('totalPoint')[0].totalPoint

    def get_queryset(self):
        self.process()
        return Match.objects.filter(date__gte=self.monday_of_last_week, date__lt=self.monday_of_this_week)

    def get_context_data(self, **kwargs):
        self.process()
        context = super(StaticsView, self).get_context_data(**kwargs)
        context['minG1'] = self.minGoal1
        context['minG2'] = self.minGoal2
        context['maxG1'] = self.maxGoal1
        context['maxG2'] = self.maxGoal2
        context['nbrMatch'] = self.nbrMatch
        context['sumGoal'] = self.sumGoal
        context['bestTeam'] = self.bestTeam
        context['badTeam'] = self.badTeam
        context['maxPoints'] = self.maxPoints
        context['minPoints'] = self.minPoints
        return context

soccerApp/templates/soccerApp/base.html
<!DOCTYPE html>
<html>
<head>

	<title>{% block title %}Soccer Ytec{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'soccerApp/style.css' %}">

</head>
<body>

   <nav class="navbar navbar-inverse">
	<div class="container-fluid">

        <!-- header -->
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
		    	<span class="icon-bar"></span>
		    	<span class="icon-bar"></span>
		    	<span class="icon-bar"></span>
		    </button>
			<a class="navbar-brand " href="{% url 'soccerApp:index' %}">Soccer Ytec</a>
		</div>



           <!-- Items -->
	    <div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'soccerApp:statics' %}">
						<span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp;Statics
					</a>
				</li>

			</ul>
		</div>
	</div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

soccerApp/templates/soccerApp/details.html
{% extends 'soccerApp/base.html' %}
{% block title %}Team details - Soccer{% endblock %}
{% block body %}

<br>
<br>

<div class="container">
    			
		<div class="row">
			<div class="col-sm-3">
				<div class="rating-block">
					<h4>{{team.nameTeam}}</h4>
					<h2 class="bold padding-bottom-7">{{team.totalVictories}}<small>/{{team.playedGames}}</small></h2>
						
					  		{{team.totalPoint}} &nbsp;<span class="glyphicon glyphicon-star red" aria-hidden="true"></span>
					  	
				</div>
			</div>
						
		</div>			
		
		<div class="row">
			<div class="col-sm-7">
				<hr/>
				<div class="review-block">
					<div class="row">
						<div class="col-sm-9">
							<div class="review-block-title">Summary</div>
							<div class="review-block-description">{{team.summary}}</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
    </div> <!-- /container -->

{% endblock %}


    

soccerApp/templates/soccerApp/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{field.errors}}</span>
		</div>		
		<label class="control-label col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10">{{field}}</div>
	</div>
{% endfor %}

soccerApp/templates/soccerApp/index.html
{% extends 'soccerApp/base.html' %}
{% load mathfilters %}
{% block body %}
{% if all_teams %}
<div class="container">
<h4>Soccer Results</h4>
	
<div class="container">
	<div class="row">
        <div class="col-md-3">
        </div>
		<div class="col-md-9">
    	 <table class="table">
                    <thead>
                        <tr>
                            <th>Team</th>
                            <th>Score</th>
                            <th>total point</th>
                            <th>Played Games</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for team in all_teams %}
                        <tr>
                            <td><a href="{% url 'soccerApp:details' team.id %}">{{team.nameTeam}}</a></td>
                            <td><div class="progress" style="height:9px; margin:8px 0;"><div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="7" aria-valuemin="0" aria-valuemax="10" style="width: {{team.totalPoint|div:maxPoints|mul:100}}%"></div></div></td>
                            <td>{{team.totalPoint}}</td>
                            <td>{{team.playedGames}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>   
		</div>
	</div>
</div>
</div>

{% endif %}
{% endblock %}

soccerApp/templates/soccerApp/statics.html
{% extends 'soccerApp/base.html' %}
{% load mathfilters %}
{% block title %}Weekly statics - Soccer{% endblock %}

{% block body %}
{% if all_matchs %}

<div class="container">
<h1 class="page-header">Statistics about last week</h1>
	<div class="row">
    <div class="col-sm-12">
<h3>Matches played</h3>
</div>
<div class="col-sm-6">

<div class="col-sm-6">
<div class="text-muted">
{% for match in all_matchs %}
<p>{{match.team1}} VS {{match.team2}} <span class="pull-right">{{match.nbGoals1}} - {{match.nbGoals2}} </span></p>
{% endfor %}
</div>
</div>
<div class="col-sm-6">
<h4>Total matches last week :  <span class="pull-right">{{nbrMatch}}</span></h4>
<p class="text-primary planned">Max goals for last week : <span class="pull-right">{%if maxG1 > maxG2 %}{{maxG1}}{% else %}{{maxG2}}{% endif %}</span></p>
<p class="text-danger">Min goals for last week : <span class="pull-right">{%if minG1 < minG2 %}{{minG1}}{% else %}{{minG2}}{% endif %}</span></p>
</div>

	
     
         
	</div>
    <div class="col-sm-6">
    <h6>The best and the bad team of the week</h6>
<div class="progress">
            <div class="progress-bar progress-bar-success " style="width: {{maxPoints|div:maxPoints|add:minPoints|mul:10}}%">
              <span class="ng-binding">{{bestTeam}} with {{maxPoints}} points</span>
            </div>
            <div class="progress-bar progress-bar-primary nonplanned" style="width: {{minPoints|div:maxPoints|add:minPoints|mul:10}}%">
              <span class="ng-binding">{{badTeam}} with {{minPoints}} points</span>
            </div>
            <div class="progress-bar progress-bar-clear pull-right" style="width: 0%">
              <span class="ng-binding"></span>
            </div>
          </div>

          </div>
</div>
    <hr>

    
</div>

{% endif %}
{% endblock %}

soccerApp/templates/soccerApp/team_form.html
{% extends 'soccerApp/base.html' %}
{% block title %}Add new team{% endblock %}
{% block body %}

<form class="form-horizontal" action="" method="post">

	{% csrf_token%}
	{% include 'soccerApp/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">

			<button type="submit" class="btn btn-success">Submit </button>
			
		</div>
	</div>
	

</form>

{% endblock %}